### Resgister User
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "demo@gmail.com",
    "password": "Secret@123",
    "firstName": "Demo",
    "lastName": "Demo"
}

### User Login
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "demo@gmail.com",
    "password": "Secret@123"
}

### Get User Profile
GET http://localhost:3000/users/me
Authorization: Bearer 

### Update User
PATCH http://localhost:3000/users
content-type: application/json
Authorization: Bearer 

{
    "email": "updatedemo@gmail.com",
    "firstName": "Update",
    "lastName": "Demo"
}

### Get  All Bookmark
GET http://localhost:3000/bookmarks
Authorization: Bearer 

### Get Bookmark By ID
GET http://localhost:3000/bookmarks/2
Authorization: Bearer 

### Create Bookmark
POST http://localhost:3000/bookmarks
content-type: application/json
Authorization: Bearer 

{
    "title": "Docker Compose with Postgres",
    "description": "Setting up Docker Compose with Postgres",
    "link": "https://www.youtube.com/watch?v=EsmbMLwDmik"
}

### Update Bookmark
PATCH http://localhost:3000/bookmarks/2
content-type: application/json
Authorization: Bearer 

{
    "title": "Update Docker Compose with Postgres",
    "description": "Update Setting up Docker Compose with Postgres",
    "link": "https://www.youtube.com/watch?v=EsmbMLwDmik"
}

### Delete Bookmark
DELETE http://localhost:3000/bookmarks/2
Authorization: Bearer 
